language: node_js
node_js:
  - "14"
before_script:
  - cd testeee
  - npm install
script: npm run build
deploy:
  local-dir: testeee/www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false
